#!/usr/bin/env python

import sys
import os.path
import logging

import mapzen.whosonfirst.search
import mapzen.whosonfirst.index

if __name__ == '__main__':

    import optparse
    opt_parser = optparse.OptionParser()

    opt_parser.add_option('--index', dest='index', action='store', default='spelunker', help='Where to write the records to (default is spelunker)')
    opt_parser.add_option('--host', dest='host', action='store', default='localhost', help='What host your search index lives (default is localhost)')
    opt_parser.add_option('--port', dest='port', action='store', default=9200, help='What port your search index lives on (default is 9200)')
    opt_parser.add_option('--timeout', dest='timeout', action='store', default=600, help='Timeout in seconds for talking to you search index lives on (default is 600)')

    opt_parser.add_option('-v', '--verbose', dest='verbose', action='store_true', default=False, help='Be chatty (default is false)')

    options, args = opt_parser.parse_args()

    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)
    else:
        logging.basicConfig(level=logging.INFO)

    logging.warning("THIS TOOL IS DEPRECRATED. PLEASE JUST USE wof-es-index INSTEAD")
    
    search_idx = mapzen.whosonfirst.search.index(host=options.host, port=options.port, timeout=options.timeout, index=options.index)

    def cb(f):

        if not search_idx.index_feature(f):
            raise Exception, "failed to index %s" % f["properties"]["wof:id"]
        
    idx = mapzen.whosonfirst.index.indexer("files", cb)
    idx.index_paths(args)
        
    sys.exit()
